from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

from pydantic import BaseModel, Field

from backend.proxy.oauth_profile import get_required_scopes
from backend.proxy.proxy_models import ToolProxyAuthorizeRequest, ToolProxyAuthorizeResponse
from backend.proxy.two_phase_tool_proxy_service import (
    execute_tool_with_capability,
    prepare_tool_authorization,
)


class LLMToolCallRunRequest(BaseModel):
    """
    OpenAI-compatible tool-call adapter request.

    This adapter accepts structured tool calls generated by real LLM providers,
    including OpenAI / DeepSeek / other OpenAI-compatible formats.

    Supported input examples:

    1. OpenAI tool_calls style:
    {
      "tool_calls": [
        {
          "type": "function",
          "function": {
            "name": "file.read",
            "arguments": "{\"path\":\"public/notice.txt\"}"
          }
        }
      ]
    }

    2. function_call style:
    {
      "function_call": {
        "name": "file.read",
        "arguments": "{\"path\":\"public/notice.txt\"}"
      }
    }

    3. Direct AgentGuard style:
    {
      "tool": "file.read",
      "params": {"path": "public/notice.txt"}
    }

    Important:
    The LLM only proposes a tool call. AgentGuard still decides whether the call
    may be authorized, whether a capability token should be issued, and whether
    it can enter the sandbox.
    """

    user: str = Field(default="user")
    original_task: str = Field(default="")
    llm_tool_call: Dict[str, Any] = Field(default_factory=dict)

    agent_platform: str = Field(default="openai_compatible")
    auth_mode: str = Field(default="oauth_scope")
    declared_scopes: Optional[List[str]] = Field(
        default=None,
        description=(
            "If omitted, the adapter declares exactly the scopes required by "
            "the proposed tool call. For OAuth-only failure demos, pass an "
            "insufficient scope list manually."
        ),
    )
    oauth_token_claims: Dict[str, Any] = Field(default_factory=dict)

    sandbox_profile: str = Field(default="")
    agent_confidence: float = Field(default=0.95, ge=0.0, le=1.0)
    input_labels: List[str] = Field(default_factory=list)
    input_from_steps: List[int] = Field(default_factory=list)

    execute: bool = Field(
        default=True,
        description=(
            "When true, run prepare -> capability token -> execute. "
            "When false, only run prepare."
        ),
    )


class ParsedToolCall(BaseModel):
    tool: str
    params: Dict[str, Any] = Field(default_factory=dict)
    source_format: str = "unknown"


def _parse_json_like_arguments(value: Any) -> Dict[str, Any]:
    if value is None:
        return {}

    if isinstance(value, dict):
        return dict(value)

    if isinstance(value, str):
        text = value.strip()
        if not text:
            return {}
        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            return {"raw_arguments": text}
        return parsed if isinstance(parsed, dict) else {"value": parsed}

    return {"value": value}


def parse_openai_compatible_tool_call(payload: Dict[str, Any]) -> ParsedToolCall:
    """
    Parse the first tool call from common LLM tool-calling response formats.
    """

    data: Dict[str, Any] = dict(payload or {})

    if isinstance(data.get("tool_call"), dict):
        data = dict(data["tool_call"])

    tool_calls = data.get("tool_calls")
    if isinstance(tool_calls, list) and tool_calls:
        first = tool_calls[0]
        if isinstance(first, dict):
            data = dict(first)

    if isinstance(data.get("function_call"), dict):
        function_call = data["function_call"]
        return ParsedToolCall(
            tool=str(function_call.get("name", "")).strip(),
            params=_parse_json_like_arguments(function_call.get("arguments")),
            source_format="function_call",
        )

    if isinstance(data.get("function"), dict):
        function = data["function"]
        return ParsedToolCall(
            tool=str(function.get("name", "")).strip(),
            params=_parse_json_like_arguments(function.get("arguments")),
            source_format="tool_calls.function",
        )

    if "name" in data and "arguments" in data:
        return ParsedToolCall(
            tool=str(data.get("name", "")).strip(),
            params=_parse_json_like_arguments(data.get("arguments")),
            source_format="name_arguments",
        )

    if "tool" in data or "tool_name" in data:
        params = data.get("params") or data.get("arguments") or {}
        if not isinstance(params, dict):
            params = _parse_json_like_arguments(params)

        return ParsedToolCall(
            tool=str(data.get("tool") or data.get("tool_name") or "").strip(),
            params=params,
            source_format="agentguard_direct",
        )

    return ParsedToolCall(tool="", params={}, source_format="unrecognized")


def infer_sandbox_profile(tool: str, params: Dict[str, Any]) -> str:
    tool = str(tool or "").strip().lower()
    path = str(
        params.get("path")
        or params.get("file_path")
        or params.get("resource")
        or params.get("filename")
        or ""
    ).lower().replace("\\", "/")

    if tool == "file.read":
        if any(marker in path for marker in ["secret", "private", ".env", "../"]):
            return "strict"
        return "local_readonly"

    if tool in {"file.write", "email.send"}:
        return "local_safe_write"

    if tool == "file.delete":
        return "strict"

    if tool == "shell.run":
        return "no_shell"

    return "default"


def build_proxy_request_from_tool_call(
    request: LLMToolCallRunRequest,
) -> Tuple[ParsedToolCall, ToolProxyAuthorizeRequest, Dict[str, Any]]:
    parsed = parse_openai_compatible_tool_call(request.llm_tool_call)

    scopes = request.declared_scopes
    if scopes is None:
        scopes = get_required_scopes(parsed.tool, parsed.params)

    sandbox_profile = request.sandbox_profile or infer_sandbox_profile(parsed.tool, parsed.params)

    claims = dict(request.oauth_token_claims or {})
    claims.setdefault("sub", f"{request.agent_platform}-agent")
    claims.setdefault("client_id", f"{request.agent_platform}-tool-caller")
    claims.setdefault("scope", " ".join(scopes))

    proxy_request = ToolProxyAuthorizeRequest(
        user=request.user,
        original_task=request.original_task,
        tool=parsed.tool,
        params=parsed.params,
        input_labels=request.input_labels,
        input_from_steps=request.input_from_steps,
        agent_confidence=request.agent_confidence,
        execute=False,
        agent_platform=request.agent_platform,
        auth_mode=request.auth_mode,
        requested_scopes=scopes,
        oauth_token_claims=claims,
        sandbox_profile=sandbox_profile,
        external_agent_metadata={
            "adapter": "openai_compatible_tool_call_adapter",
            "source_format": parsed.source_format,
            "received_at": datetime.now(timezone.utc).isoformat(),
            "note": (
                "LLM proposes the tool call; AgentGuard decides whether it may run."
            ),
        },
    )

    adapter_evidence = {
        "adapter": "openai_compatible_tool_call_adapter",
        "source_format": parsed.source_format,
        "parsed_tool": parsed.tool,
        "parsed_params": parsed.params,
        "declared_scopes": scopes,
        "sandbox_profile": sandbox_profile,
        "security_boundary": (
            "LLM output is treated as untrusted input and must pass Tool Proxy "
            "two-phase authorization."
        ),
    }

    return parsed, proxy_request, adapter_evidence


def run_llm_tool_call_through_agentguard(
    request: LLMToolCallRunRequest,
) -> Dict[str, Any]:
    parsed, proxy_request, adapter_evidence = build_proxy_request_from_tool_call(request)

    if not parsed.tool:
        return {
            "success": False,
            "mode": "llm_tool_call_adapter",
            "message": "No supported tool call could be parsed from the LLM output.",
            "adapter_evidence": adapter_evidence,
            "phase1": None,
            "phase2": None,
            "final_decision": "deny",
            "executed": False,
        }

    phase1: ToolProxyAuthorizeResponse = prepare_tool_authorization(proxy_request)

    phase2: Optional[ToolProxyAuthorizeResponse] = None
    if request.execute and phase1.decision == "allow":
        token = str(phase1.capability_token.get("token", ""))
        execute_request = proxy_request.model_copy(
            update={
                "execute": True,
                "capability_token": token,
            }
        )
        phase2 = execute_tool_with_capability(execute_request)

    return {
        "success": True,
        "mode": "llm_tool_call_adapter",
        "message": (
            "LLM tool call passed through AgentGuard prepare -> capability token -> sandbox execution."
            if phase2 is not None
            else "LLM tool call completed AgentGuard prepare phase only."
        ),
        "adapter_evidence": adapter_evidence,
        "phase1": phase1.model_dump(),
        "phase2": phase2.model_dump() if phase2 is not None else None,
        "final_decision": phase2.decision if phase2 is not None else phase1.decision,
        "executed": bool(phase2.executed) if phase2 is not None else False,
    }
