from pydantic import BaseModel, Field
from typing import Dict, Any, List, Optional


class ToolCallRequest(BaseModel):
    user: str = "user"
    tool: str
    params: Dict[str, Any] = Field(default_factory=dict)

    # Preserve the original user task/input so Gateway semantic checks and
    # audit records can evaluate the tool call in context.
    original_input: Optional[str] = None

    # Task13锛氫换鍔℃巿鏉冨悎绾?
    task_contract: Optional[Dict[str, Any]] = None
    input_labels: List[str] = Field(default_factory=list)
    current_step: int = 1
    used_risk: int = 0
    history: List[Dict[str, Any]] = Field(default_factory=list)

    agent_confidence: Optional[float] = None
    plan_status: Optional[str] = None
    plan_warnings: List[str] = Field(default_factory=list)


class ToolCallPlan(BaseModel):
    """
    Structured tool-call plan generated by an Agent.
    It is only a plan and must still pass through PlanGuard and Gateway.
    """
    tool_name: str
    description: str = ""
    arguments: Dict[str, Any] = Field(default_factory=dict)
    need_auth: bool = True


class AgentPlanResult(BaseModel):
    """
    Unified Agent output for FakeAgent and LLMAgent.
    """

    agent: str
    status: str
    original_input: str
    tool_call: Optional[ToolCallPlan] = None
    message: Optional[str] = None
    raw_output: Optional[str] = None

    # Task14 鏂板锛氳鍒掕川閲忓瓧娈?
    confidence: float = 0.0
    missing_params: List[str] = Field(default_factory=list)
    unsupported_reason: Optional[str] = None
    clarification_question: Optional[str] = None


class GatewayResponse(BaseModel):
    """
    鎺堟潈缃戝叧鍒ゆ柇缁撴灉銆?
    decision:
    - allow锛氬厑璁告墽琛?
    - confirm锛氶渶瑕佷汉宸ョ‘璁?
    - deny锛氭嫆缁濇墽琛?
    """

    decision: str
    risk_score: int
    risk_level: str = "low"
    reason: List[str]
    explanations: List[Dict[str, Any]] = Field(default_factory=list)


class AgentTextRequest(BaseModel):
    """
    妯℃嫙鏅鸿兘浣撹緭鍏ヨ姹傘€?
    user锛氬綋鍓嶇敤鎴?
    user_input锛氳嚜鐒惰瑷€浠诲姟
    """

    user: str = "test_user"
    user_input: str


class ApprovalRejectRequest(BaseModel):
    """
    浜哄伐鎷掔粷纭璇锋眰銆?
    """

    reason: Optional[str] = "浜哄伐鎷掔粷鎵ц"

