from pydantic import BaseModel, Field
from typing import Dict, Any, List, Optional


class ToolCallRequest(BaseModel):
    user: str = "user"
    tool: str
    params: Dict[str, Any] = Field(default_factory=dict)

    # Preserve the original user task/input so Gateway semantic checks and
    # audit records can evaluate the tool call in context.
    original_input: Optional[str] = None

    # Task13：任务授权合约
    task_contract: Optional[Dict[str, Any]] = None
    input_labels: List[str] = Field(default_factory=list)
    current_step: int = 1
    used_risk: int = 0

    agent_confidence: Optional[float] = None
    plan_status: Optional[str] = None
    plan_warnings: List[str] = Field(default_factory=list)


class ToolCallPlan(BaseModel):
    """
    Structured tool-call plan generated by an Agent.
    It is only a plan and must still pass through PlanGuard and Gateway.
    """
    tool_name: str
    description: str = ""
    arguments: Dict[str, Any] = Field(default_factory=dict)
    need_auth: bool = True


class AgentPlanResult(BaseModel):
    """
    Unified Agent output for FakeAgent and LLMAgent.
    """

    agent: str
    status: str
    original_input: str
    tool_call: Optional[ToolCallPlan] = None
    message: Optional[str] = None
    raw_output: Optional[str] = None

    # Task14 新增：计划质量字段
    confidence: float = 0.0
    missing_params: List[str] = Field(default_factory=list)
    unsupported_reason: Optional[str] = None
    clarification_question: Optional[str] = None


class GatewayResponse(BaseModel):
    """
    授权网关判断结果。
    decision:
    - allow：允许执行
    - confirm：需要人工确认
    - deny：拒绝执行
    """

    decision: str
    risk_score: int
    risk_level: str = "low"
    reason: List[str]
    explanations: List[Dict[str, Any]] = Field(default_factory=list)


class AgentTextRequest(BaseModel):
    """
    模拟智能体输入请求。
    user：当前用户
    user_input：自然语言任务
    """

    user: str = "test_user"
    user_input: str


class ApprovalRejectRequest(BaseModel):
    """
    人工拒绝确认请求。
    """

    reason: Optional[str] = "人工拒绝执行"
