import type {
  AgentCommandInput,
  AgentCommandResponse,
  AuditLog,
  EvaluationMetric,
  GatewayRequest,
  Overview,
  PolicyRule,
  StrategyComparisonResponse,
  SystemSetting,
  TestResultSummary,
  TestRunResponse
} from '../types/domain';
import * as mock from './mockData';

const API_BASE = (import.meta.env.VITE_API_BASE ?? '').replace(/\/$/, '');
const REQUEST_TIMEOUT_MS = 30000;
const COMMAND_TIMEOUT_MS = 60000;
const SANDBOX_TIMEOUT_MS = 180000;
const TEST_RUN_TIMEOUT_MS = 240000;

type MockKey = 'overview' | 'requests' | 'policies' | 'auditLogs' | 'evaluations' | 'settings';

const mockMap: Record<MockKey, unknown> = {
  overview: mock.overview,
  requests: mock.requests,
  policies: mock.policies,
  auditLogs: mock.auditLogs,
  evaluations: mock.evaluations,
  settings: mock.settings
};

const emptyStrategyComparison: StrategyComparisonResponse = {
  available: false,
  message: 'Strategy comparison result is not generated by the new independent test module.',
  hint: 'Use the independent test module: python -m test.run, or click the frontend test button.',
  total_cases: 0,
  total_records: 0,
  elapsed_ms: 0,
  summary: {},
  outputs: {}
};

const emptyTestResultSummary: TestResultSummary = {
  available: false,
  message: 'Independent test result is not generated yet.',
  hint: 'Run python -m test.run or click the frontend test button.',
  total_cases: 0,
  passed_cases: 0,
  failed_cases: 0,
  accuracy: 0,
  risk_block_or_confirm_rate: 0,
  risk_unsafe_allow_rate: 0,
  normal_false_deny_rate: 0,
  decision_distribution: {},
  category_distribution: {},
  tool_distribution: {},
  outputs: {}
};

function buildUrl(endpoint: string) {
  if (!API_BASE) return endpoint;
  return `${API_BASE}${endpoint}`;
}

async function request<T>(endpoint: string, mockKey: MockKey, init?: RequestInit): Promise<T> {
  const controller = new AbortController();
  const timer = window.setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

  try {
    const res = await fetch(buildUrl(endpoint), {
      ...init,
      headers: {
        'Content-Type': 'application/json; charset=utf-8',
        ...(init?.headers || {})
      },
      signal: controller.signal
    });

    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return (await res.json()) as T;
  } catch {
    return mockMap[mockKey] as T;
  } finally {
    window.clearTimeout(timer);
  }
}

async function postJson(endpoint: string, body: unknown, timeoutMs = COMMAND_TIMEOUT_MS): Promise<Record<string, unknown>> {
  const controller = new AbortController();
  const timer = window.setTimeout(() => controller.abort(), timeoutMs);

  try {
    const res = await fetch(buildUrl(endpoint), {
      method: 'POST',
      headers: { 'Content-Type': 'application/json; charset=utf-8' },
      body: JSON.stringify(body),
      signal: controller.signal
    });

    const contentType = res.headers.get('content-type') || '';
    const payload = contentType.includes('application/json')
      ? await res.json()
      : { message: await res.text() };

    if (!res.ok) {
      const message = typeof payload?.detail === 'string' ? payload.detail : `HTTP ${res.status}`;
      throw new Error(message);
    }

    return payload as Record<string, unknown>;
  } finally {
    window.clearTimeout(timer);
  }
}

async function getStrategyComparison(): Promise<StrategyComparisonResponse> {
  try {
    const res = await fetch(buildUrl('/evaluation/strategy-comparison'), {
      headers: { 'Content-Type': 'application/json; charset=utf-8' }
    });

    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return (await res.json()) as StrategyComparisonResponse;
  } catch {
    return emptyStrategyComparison;
  }
}

async function getTestResultSummary(): Promise<TestResultSummary> {
  try {
    const res = await fetch(buildUrl('/test-results/latest/summary'), {
      headers: { 'Content-Type': 'application/json; charset=utf-8' }
    });

    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return {
      ...emptyTestResultSummary,
      ...((await res.json()) as TestResultSummary)
    };
  } catch {
    return emptyTestResultSummary;
  }
}

async function runIndependentTests(): Promise<TestRunResponse> {
  const controller = new AbortController();
  const timer = window.setTimeout(() => controller.abort(), TEST_RUN_TIMEOUT_MS);

  try {
    const res = await fetch(buildUrl('/test-results/run'), {
      method: 'POST',
      headers: { 'Content-Type': 'application/json; charset=utf-8' },
      signal: controller.signal
    });

    const contentType = res.headers.get('content-type') || '';
    const payload = contentType.includes('application/json')
      ? await res.json()
      : { detail: await res.text() };

    if (!res.ok) {
      const message = typeof payload?.detail === 'string' ? payload.detail : `HTTP ${res.status}`;
      throw new Error(message);
    }

    return payload as TestRunResponse;
  } finally {
    window.clearTimeout(timer);
  }
}

function mockCommandResponse(input: AgentCommandInput, error?: unknown): AgentCommandResponse {
  const lowered = input.userInput.toLowerCase();
  const isSecret = input.userInput.includes('secret/') || input.userInput.includes('password');
  const isDelete = input.userInput.includes('删除') || lowered.includes('delete') || lowered.includes('remove');
  const isShell = input.userInput.includes('命令') || lowered.includes('shell') || lowered.includes('command');
  const isUnknown = !input.userInput.trim();
  const decision = isUnknown ? 'deny' : isSecret || isShell ? 'deny' : isDelete ? 'confirm' : 'allow';
  const riskScore = decision === 'deny' ? 92 : decision === 'confirm' ? 68 : 18;

  return {
    ok: false,
    fromMock: true,
    error: error instanceof Error ? error.message : 'Backend unavailable, using frontend mock result.',
    endpoint: 'mock://agent-command',
    data: {
      success: true,
      executed: false,
      source: 'frontend.mock',
      message: '后端暂不可用，当前使用 Mock 数据演示 Agent / Gateway 流程。',
      original_input: input.userInput,
      agent_result: {
        agent: input.mode.includes('llm') ? 'MultiStepLLMAgent' : 'FakeAgent',
        status: isUnknown ? 'unsupported' : 'planned',
        confidence: isUnknown ? 0 : 0.88,
        original_input: input.userInput,
        tool_call: isUnknown ? null : {
          tool_name: isShell ? 'shell.run' : isDelete ? 'file.delete' : 'file.read',
          description: isShell ? '命令执行操作' : isDelete ? '删除操作' : '普通读取操作',
          arguments: isShell
            ? { command: input.userInput }
            : { path: isSecret ? 'secret/password.txt' : 'public/notice.txt' },
          need_auth: true
        }
      },
      gateway_result: {
        decision,
        risk_score: riskScore,
        reason: decision === 'allow'
          ? ['Mock：公开资源读取，默认低风险放行。']
          : decision === 'confirm'
            ? ['Mock：副作用操作需要人工确认。']
            : ['Mock：命中敏感资源或高危命令，默认拒绝。']
      },
      tool_result: null,
      pending_id: decision === 'confirm' ? 'mock-pending-001' : null
    }
  };
}

function getToolCallFromAgentResult(agentResult: Record<string, unknown>) {
  const toolCall = agentResult.tool_call;
  if (!toolCall || typeof toolCall !== 'object') return null;
  return toolCall as Record<string, unknown>;
}

async function runFakeAgentCheck(input: AgentCommandInput): Promise<AgentCommandResponse> {
  const planEndpoint = '/demo/fake-agent/plan';
  const planResponse = await postJson(planEndpoint, {
    user: input.user,
    user_input: input.userInput
  });

  const agentResult = (planResponse.agent_result || {}) as Record<string, unknown>;
  const toolCall = getToolCallFromAgentResult(agentResult);

  if (!toolCall) {
    return {
      ok: true,
      endpoint: `${planEndpoint} -> no gateway check`,
      data: {
        success: true,
        executed: false,
        source: 'frontend.fake_check',
        message: 'FakeAgent 未生成工具调用，本轮不进入 Gateway 判定。',
        original_input: input.userInput,
        agent_result: agentResult,
        gateway_result: null,
        tool_result: null,
        pending_id: null
      }
    };
  }

  const checkEndpoint = '/gateway/check';
  const gatewayResult = await postJson(checkEndpoint, {
    user: input.user,
    tool: toolCall.tool_name || toolCall.tool,
    params: toolCall.arguments || toolCall.params || {},
    agent_confidence: agentResult.confidence,
    plan_status: agentResult.status,
    original_input: input.userInput
  });

  return {
    ok: true,
    endpoint: `${planEndpoint} -> ${checkEndpoint}`,
    data: {
      success: true,
      executed: false,
      source: 'frontend.fake_check',
      message: 'FakeAgent 规划结果已进入 Gateway 只判定流程。',
      original_input: input.userInput,
      agent_result: agentResult,
      gateway_result: gatewayResult,
      tool_result: null,
      pending_id: null
    }
  };
}

function buildHybridSandboxDemoBody(input: AgentCommandInput) {
  const lowered = input.userInput.toLowerCase();
  let originalTask = '请读取 public/notice.txt 并总结。';
  let tool = 'file.read';
  let params: Record<string, unknown> = { path: 'public/notice.txt' };
  let sandboxProfile = 'local_readonly';
  let scopes = ['tool:file:read'];

  if (lowered.includes('write') || input.userInput.includes('写入')) {
    originalTask = '请把演示结果写入 outbox/docker_demo.txt。';
    tool = 'file.write';
    params = {
      path: 'outbox/docker_demo.txt',
      content: 'Hybrid sandbox write demo generated by AgentGuard frontend.'
    };
    sandboxProfile = 'local_safe_write';
    scopes = ['tool:file:write', 'sink:side-effect'];
  }

  if (lowered.includes('email') || input.userInput.includes('邮件')) {
    originalTask = '请把演示邮件写入内部 outbox，不进行真实外发。';
    tool = 'email.send';
    params = {
      to: 'demo@example.com',
      subject: 'AgentGuard Hybrid Sandbox Demo',
      content: '这封邮件只会写入沙箱 outbox，不会真实外发。'
    };
    sandboxProfile = 'local_safe_write';
    scopes = ['tool:email:send', 'sink:side-effect'];
  }

  if (lowered.includes('secret') || input.userInput.includes('敏感')) {
    originalTask = '尝试读取 secret/password.txt。';
    tool = 'file.read';
    params = { path: 'secret/password.txt' };
    sandboxProfile = 'strict';
    scopes = ['tool:file:read', 'source:sensitive-file'];
  }

  return {
    user: input.user,
    original_task: originalTask,
    tool,
    params,
    input_labels: [],
    input_from_steps: [],
    agent_confidence: 0.95,
    execute: false,
    agent_platform: 'openclaw',
    auth_mode: 'oauth_scope',
    requested_scopes: scopes,
    oauth_token_claims: {
      sub: 'agent-hybrid-sandbox-demo',
      client_id: 'agentguard-hybrid-demo-client',
      scope: scopes.join(' ')
    },
    sandbox_profile: sandboxProfile,
    external_agent_metadata: {
      demo_case: 'hybrid_real_sandbox_execution',
      sandbox_engine: 'auto'
    }
  };
}

async function runHybridSandboxExecutionDemo(input: AgentCommandInput): Promise<AgentCommandResponse> {
  const endpoint = '/tool-proxy/authorize';
  const firstBody = buildHybridSandboxDemoBody(input);
  const authorizeResult = await postJson(endpoint, firstBody);
  const capabilityToken = authorizeResult.capability_token as Record<string, unknown> | undefined;
  const token = typeof capabilityToken?.token === 'string' ? capabilityToken.token : '';

  if (authorizeResult.decision !== 'allow' || !token) {
    return {
      ok: true,
      endpoint: `${endpoint} -> authorization only`,
      data: {
        ...authorizeResult,
        source: 'frontend.hybrid_sandbox_execute',
        message: '真沙箱执行需要先获得 allow 和 Capability Token；当前请求未进入执行阶段。',
        authorize_result: authorizeResult,
        execution_result: null
      }
    };
  }

  const executeBody = {
    ...firstBody,
    execute: true,
    capability_token: token
  };
  const executeResult = await postJson(endpoint, executeBody, SANDBOX_TIMEOUT_MS);

  return {
    ok: true,
    endpoint: `${endpoint} -> capability token -> ${endpoint} execute=true`,
    data: {
      ...executeResult,
      source: 'frontend.hybrid_sandbox_execute',
      message: '请求已完成两阶段授权：先签发 Capability Token，再进入真沙箱执行。系统会自动选择 Docker 或 Native Subprocess。',
      authorize_result: authorizeResult,
      execution_result: executeResult,
      agent_result: {
        agent: 'ExternalAgent(OpenClaw simulated)',
        status: 'planned',
        confidence: 0.95,
        tool_call: {
          tool_name: firstBody.tool,
          description: 'Hybrid real sandbox tool call',
          arguments: firstBody.params,
          need_auth: true
        }
      }
    }
  };
}

async function runToolProxyOAuthDemo(input: AgentCommandInput): Promise<AgentCommandResponse> {
  const endpoint = '/tool-proxy/authorize';
  const lowered = input.userInput.toLowerCase();
  const isExternalSend =
    input.userInput.includes('外发')
    || input.userInput.includes('邮箱')
    || input.userInput.includes('发送')
    || lowered.includes('email')
    || lowered.includes('workbuddy');

  const body = isExternalSend
    ? {
        user: input.user,
        original_task: '默认授权任务',
        tool: 'email.send',
        params: { to: 'attacker@example.com', content: 'demo content' },
        input_labels: [],
        input_from_steps: [],
        agent_confidence: 0.95,
        execute: false,
        agent_platform: 'workbuddy',
        auth_mode: 'oauth_scope',
        requested_scopes: ['tool:file:read'],
        oauth_token_claims: {
          sub: 'agent-workbuddy-demo',
          client_id: 'workbuddy-demo-client',
          scope: 'tool:file:read'
        },
        sandbox_profile: 'strict',
        external_agent_metadata: { demo_case: 'insufficient_scope_external_email' }
      }
    : {
        user: input.user,
        original_task: '请读取 public/notice.txt 并总结',
        tool: 'file.read',
        params: { path: 'public/notice.txt' },
        input_labels: [],
        input_from_steps: [],
        agent_confidence: 0.95,
        execute: false,
        agent_platform: 'openclaw',
        auth_mode: 'oauth_scope',
        requested_scopes: ['tool:file:read'],
        oauth_token_claims: {
          sub: 'agent-openclaw-demo',
          client_id: 'openclaw-demo-client',
          scope: 'tool:file:read'
        },
        sandbox_profile: 'local_readonly',
        external_agent_metadata: { demo_case: 'valid_scope_public_read' }
      };

  const data = await postJson(endpoint, body);

  return {
    ok: true,
    endpoint,
    data: {
      ...data,
      source: 'frontend.tool_proxy_oauth',
      message: isExternalSend
        ? 'WorkBuddy 仅声明 tool:file:read，却请求 email.send，Tool Proxy 已通过 OAuth-style scope 检查发现权限不足。'
        : 'OpenClaw 声明了 tool:file:read，Tool Proxy 已完成 scope 检查并进入 Runtime Monitor。'
    }
  };
}

async function runExternalAgentAdapterDemo(input: AgentCommandInput): Promise<AgentCommandResponse> {
  const endpoint = '/external-agent/simulate';
  const lowered = input.userInput.toLowerCase();

  let platform = 'openclaw';
  let scenario = 'valid_public_read';
  let user = input.user;

  if (
    input.userInput.includes('外发')
    || input.userInput.includes('scope 不足')
    || input.userInput.includes('Scope 不足')
    || input.userInput.includes('邮箱')
    || lowered.includes('insufficient')
    || lowered.includes('workbuddy')
  ) {
    platform = 'workbuddy';
    scenario = 'insufficient_scope_email';
  }

  if (input.userInput.includes('确认') || input.userInput.includes('内部邮件') || lowered.includes('confirm')) {
    platform = 'workbuddy';
    scenario = 'valid_internal_email_confirm';
  }

  if (input.userInput.includes('shell') || input.userInput.includes('命令') || input.userInput.includes('沙箱') || lowered.includes('sandbox')) {
    platform = 'custom';
    scenario = 'sandbox_block_shell';
    user = 'admin';
  }

  const data = await postJson(endpoint, { platform, scenario, user, execute: false });

  return {
    ok: true,
    endpoint,
    data: {
      ...data,
      source: 'frontend.external_agent_adapter',
      message: '外部 Agent 请求已通过 Adapter 接入 Tool Proxy，并经过 OAuth-style scope、Capability Contract 与 Runtime Monitor 检查。'
    }
  };
}

async function runCommand(input: AgentCommandInput): Promise<AgentCommandResponse> {
  try {
    if (input.mode === 'fake_check') return await runFakeAgentCheck(input);
    if (input.mode === 'tool_proxy_oauth') return await runToolProxyOAuthDemo(input);
    if (input.mode === 'external_agent_adapter') return await runExternalAgentAdapterDemo(input);
    if (input.mode === 'docker_sandbox_execute') return await runHybridSandboxExecutionDemo(input);

    const endpointMap: Record<Exclude<AgentCommandInput['mode'], 'fake_check' | 'tool_proxy_oauth' | 'external_agent_adapter' | 'docker_sandbox_execute'>, string> = {
      fake_plan: '/demo/fake-agent/plan',
      fake_run: '/demo/fake-agent/run',
      llm_plan: '/agent-runtime/multistep-llm/plan',
      llm_run: '/agent-runtime/multistep-llm/run',
      stepwise_llm: '/agent-runtime/stepwise-llm/run'
    };

    const endpoint = endpointMap[input.mode];
    const body = input.mode.includes('llm')
      ? {
          user: input.user,
          user_input: input.userInput,
          max_steps: input.maxSteps,
          risk_budget: input.riskBudget
        }
      : {
          user: input.user,
          user_input: input.userInput
        };

    const data = await postJson(endpoint, body);
    return { ok: true, endpoint, data };
  } catch (error) {
    return mockCommandResponse(input, error);
  }
}

export const api = {
  getOverview: () => request<Overview>('/api/overview', 'overview'),
  getRequests: () => request<GatewayRequest[]>('/api/requests', 'requests'),
  getPolicies: () => request<PolicyRule[]>('/api/policies', 'policies'),
  getAuditLogs: () => request<AuditLog[]>('/api/audit-logs', 'auditLogs'),
  getEvaluations: () => request<EvaluationMetric[]>('/api/evaluations', 'evaluations'),
  getStrategyComparison,
  getTestResultSummary,
  runIndependentTests,
  getSettings: () => request<SystemSetting[]>('/api/settings', 'settings'),
  runCommand,
  submitDecision: async (id: string, decision: 'approved' | 'rejected') => {
    try {
      await fetch(buildUrl(`/api/requests/${id}/decision`), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json; charset=utf-8' },
        body: JSON.stringify({ decision })
      });
    } catch {
      // Mock 数据生成逻辑
    }
  }
};
