from typing import Any, Dict, List

from backend.demo.fake_agent import FakeAgent
from backend.gateway import handle_tool_request
from backend.schemas import AgentPlanResult, AgentTextRequest, ToolCallRequest


DEMO_CASES: List[Dict[str, Any]] = [
    {
        "id": "read_public_file",
        "title": "读取公开文件",
        "description": "演示 FakeAgent 将自然语言转换为 file.read，然后交给 Gateway 判断。",
        "request": {"user": "user", "user_input": "读取文件 public/notice.txt"},
    },
    {
        "id": "read_secret_file",
        "title": "读取敏感文件",
        "description": "演示 Gateway 拦截对 secret/password.txt 的敏感读取。",
        "request": {"user": "user", "user_input": "读取文件 secret/password.txt"},
    },
    {
        "id": "delete_public_file",
        "title": "删除公开文件",
        "description": "演示破坏性操作进入 confirm 或 deny。",
        "request": {"user": "user", "user_input": "删除文件 public/notice.txt"},
    },
    {
        "id": "send_email",
        "title": "发送邮件",
        "description": "演示 FakeAgent 生成 email.send，并交给 Gateway 判断是否需要确认。",
        "request": {"user": "user", "user_input": "给 internal@example.com 发邮件，内容是 public notice"},
    },
    {
        "id": "shell_command",
        "title": "执行命令",
        "description": "演示管理员高风险 shell.run 请求如何被 Gateway 处理。",
        "request": {"user": "admin", "user_input": "执行命令 command=dir"},
    },
]


def _model_to_dict(model: Any) -> Any:
    if hasattr(model, "model_dump"):
        return model.model_dump()
    if hasattr(model, "dict"):
        return model.dict()
    return model


def list_demo_cases() -> Dict[str, Any]:
    return {"source": "demo", "message": "Available demo cases", "cases": DEMO_CASES}


def build_tool_request_from_plan(user: str, plan_result: AgentPlanResult, original_input: str = "") -> ToolCallRequest | None:
    if plan_result.status != "planned" or plan_result.tool_call is None:
        return None
    return ToolCallRequest(
        user=user,
        tool=plan_result.tool_call.tool_name,
        params=plan_result.tool_call.arguments,
        agent_confidence=plan_result.confidence,
        plan_status=plan_result.status,
        original_input=original_input or plan_result.original_input,
    )


def run_fake_agent_plan(request: AgentTextRequest) -> Dict[str, Any]:
    agent = FakeAgent()
    plan_result = agent.plan(request.user_input)
    return {
        "source": "demo.fake_agent",
        "message": "FakeAgent generated a demo-only tool-call plan.",
        "user": request.user,
        "original_input": request.user_input,
        "agent_result": _model_to_dict(plan_result),
    }


def run_fake_agent_demo(request: AgentTextRequest) -> Dict[str, Any]:
    agent = FakeAgent()
    plan_result = agent.plan(request.user_input)
    agent_result = _model_to_dict(plan_result)
    tool_request = build_tool_request_from_plan(
        user=request.user,
        plan_result=plan_result,
        original_input=request.user_input,
    )
    if tool_request is None:
        return {
            "success": True,
            "executed": False,
            "source": "demo.fake_agent",
            "message": "FakeAgent did not produce an executable tool call.",
            "original_input": request.user_input,
            "agent_result": agent_result,
            "gateway_result": None,
            "tool_result": None,
            "pending_id": None,
        }
    gateway_response = handle_tool_request(
        request=tool_request,
        original_input=request.user_input,
        agent_result={**agent_result, "demo_only": True, "note": "This plan was generated by backend.demo.FakeAgent."},
    )
    return {**gateway_response, "source": "demo.fake_agent", "demo_only": True, "original_input": request.user_input}


def run_demo_case(case_id: str) -> Dict[str, Any]:
    matched_case = None
    for case in DEMO_CASES:
        if case["id"] == case_id:
            matched_case = case
            break
    if matched_case is None:
        return {"success": False, "message": f"Unknown demo case: {case_id}", "available_cases": [case["id"] for case in DEMO_CASES]}
    request = AgentTextRequest(**matched_case["request"])
    result = run_fake_agent_demo(request)
    return {"success": True, "case": matched_case, "result": result}
